CypherD-IO/mobile-app

src/containers/Bridge/bridge.tsx, src/containers/Bridge/bridgeStatus.tsx
=> bridgeStatus proportions adjustments

src/containers/Portfolio/animatedComponents/AnimatedTabView.tsx, src/containers/Portfolio/index.tsx, src/containers/Portfolio/scenes/nftScene.tsx
- adjusted scrolling on moving to the nftScene.
- fixed linting errors in AnimatedTabView.
=> tabview scroll issue fix

src/components/v2/walletConnectV2Views/SigningModal.tsx
The modal was shown to be loading when an error occurs in any step of the decoding.
Changed it to show the raw data.
=> add: fallback to raw data when decode call error

src/containers/Portfolio/components/CardCarousel/CarouselItem.tsx, src/containers/Portfolio/components/CardCarousel/index.tsx
- The card carousel when containing a single card now centers the card in the section.
=> CYP-1571-Card-carousel-bug-fixes

src/containers/DebitCard/cardWaitList.tsx, src/containers/Options/index.tsx, src/containers/Qrcode/index.tsx, src/i18n/index.tsx
Text saying "11 chains" updated. Options screen logo changed. Receive page new chains included now.
=> fix: :bug: modify areas to include new chains

App.tsx
The inAppUpdate call failing now gets caught in Sentry as an exception that logs, the error, platform, platform version, appVersion.
=> refactor: :memo: add more info when inAppUpdates call fails

src/containers/DebitCard/bridgeCard/fundCard.tsx, src/models/tokenMetaData.model.ts
The check for native gas when funding the card was checking the wrong token for gas balance. Fixed this to check for balance of the native token.
=> fix: :bug: gas check on fund card

src/constants/enum.ts, src/containers/DebitCard/bridgeCard/transactionDetails.tsx, src/containers/DebitCard/bridgeCard/transactions.tsx, src/i18n/index.tsx
Adjusted spacing and alignment in Card Transactions Details page. Added Refund as a filter type in Card transaction.
=> feat: :lipstick: card txndetails page adjustment + refund filter

src/containers/Portfolio/components/BannerCarousel/BannerCarouselItem.tsx, src/i18n/index.tsx
The activity cards now show the status of the activity instead of just showing the type of the activity. And the Status bar in the card is now yellow when the status of the activity is delayed.
=> feat: :sparkles: addded status text for activity cards

src/components/v2/portfolioTokenItem.tsx, src/containers/Options/index.tsx, src/containers/Portfolio/components/Banner.tsx, src/containers/Portfolio/scenes/tokenScene.tsx
- Center aligned the HIDE/SHOW.
- Adjusted the padding in PortfolioTokenItem.
- Margined the Options screen logo into the screen.
=> Cyp 1594 2.01.0 minor adjustments

src/components/v2/CardCarousel.tsx, src/containers/DebitCard/bridgeCard/card.tsx, src/containers/DebitCard/bridgeCard/transactions.tsx
The ImageBackground used for the cards in the Cypher Card page is now replaced an absolute positioned FastImage, which stops the gltiching.
=> fix: :ambulance: card Imagebackground glitching

src/hooks/useEns/index.ts
useEns hook used to resolve the domain and address now uses web3js to call the resolving contract instead of ethers.
=> fix: :ambulance: ens domain resolving

src/components/v2/walletConnectV2Views/PairingModal.tsx, src/containers/Options/WalletConnectCamera.tsx
The dApp url has been limited to 200px width and ellipsized for any dapp urls that are really long.
=> feat: :sparkles: ellipsize dAppURL in manage connections

src/containers/DebitCard/bridgeCard/bridgeCard.tsx, src/containers/DebitCard/bridgeCard/transactions.tsx, src/routes/auth.tsx, src/routes/tabStack.tsx
Temporary patch to the excessive unecessary reloads on the Card Transactions.
=> Cyp 1600 card txns loading everytime

src/components/v2/CardTransactionItem.tsx, src/constants/enum.ts, src/containers/DebitCard/CardV2/DateRangeFilterPicker.tsx, src/containers/DebitCard/CardV2/index.tsx, src/containers/DebitCard/bridgeCard/CardTxnFilterModal.tsx, src/containers/DebitCard/bridgeCard/transactionDetails.tsx, src/containers/DebitCard/bridgeCard/transactions.tsx, src/i18n/index.tsx, src/models/card.model.ts
Handled isSettled for each transaction. Added filter based on date range and status. Refined to show appropirate details in txn details page.
=> feat: :sparkles: daterange filter, settlement status & filter, fix splicing, txndetails refinement

src/components/v2/CardTransactionItem.tsx, src/containers/DebitCard/CardV2/index.tsx, src/containers/DebitCard/bridgeCard/CardTxnFilterModal.tsx
When the txn list is either empty or not full, the list showed the bgImage. Now added a View that is attached to list items and positioned under to have a white bg. And added white bg for ListEmptyComponent
=> fix: :lipstick: white bg for the txn list when list not full

src/components/v2/GlobalModal.tsx, src/components/v2/StateModal.tsx, src/containers/DebitCard/CardV2/index.tsx, src/i18n/index.tsx
Showing the registered email to the user on exporting card transactions in the confirmation message.
=> CYP-1630-show-email-and-mobile-number-instead-of-saying-registered

src/containers/Bridge/bridge.tsx, src/containers/DebitCard/bridgeCard/fundCard.tsx
Added functionality to enable card funding with crypto. Now it works identical to the bridge Amount input.
=> feat: :sparkles: crypto input for card loading

src/components/WalletConnectModal.tsx, src/containers/Bridge/bridge.tsx, src/containers/Browser/Browser.tsx, src/containers/DebitCard/bridgeCard/fundCard.tsx, src/containers/SendTo/enterAmount.tsx, src/core/util.tsx
Changes everywhere to change the fn from getNativeTokenBalance to getNativeToken. And fix the fund card gas bug by multiplying with nativeTokenPrice instead of selectedTokenPrice
=> fix: :bug: fund card gas bug and getNativeToken util

src/components/deFiRefreshFilterBar.tsx, src/containers/Portfolio/scenes/deFiScene.tsx, src/i18n/index.tsx
=> defi total balance redesign

src/components/deFiRefreshFilterBar.tsx
Change of icon, and improved code for the DeFiFilterRefreshBar.
=> CYP-1649-Filter-Icon-in-DeFi

src/containers/DebitCard/cardWaitList.tsx
Remove country selection in card waitlist. Now clicking on the card tab in the tab stack directly shows the input field for email and the I have an invite code buttons.
=> feat: :fire: Remove country selection in card waitlist.

src/containers/Portfolio/components/BannerCarousel/index.tsx, src/containers/Portfolio/scenes/deFiScene.tsx, src/containers/Portfolio/scenes/nftScene.tsx, src/containers/Portfolio/scenes/tokenScene.tsx, src/containers/Portfolio/scenes/txnScene.tsx, src/hooks/useScrollManager/index.ts, src/i18n/index.tsx
Changed placements of the loading and other states to have proper visibility of the elements.
=> CYP-1654-Ugly-loading-portfolio

src/components/v2/ChooseCountryModal.tsx, src/containers/DebitCard/CardV2/UpgradeToPhysicalCardScreen.tsx, src/containers/DebitCard/cardSignUp.tsx, src/containers/DebitCard/cardWaitList.tsx
=> CYP-1655-add-back-country-selection-for-cardwaitlist

src/containers/Portfolio/components/BannerCarousel/index.tsx, src/containers/Portfolio/index.tsx, src/hooks/useScrollManager/index.ts
BannerCarousel now renders after the portfolio tokens are finished loading, resulting in a clean loading state.
=> fix: :sparkles: ugly portfolio loads correctly

src/components/v2/ChooseCountryModal.tsx, src/components/v2/ChooseStateFromCountryModal.tsx, src/containers/DebitCard/CardV2/ShippingDetailsOTPScreen.tsx, src/containers/DebitCard/CardV2/UpgradeToPhysicalCardScreen.tsx, src/containers/DebitCard/CardV2/index.tsx, src/containers/DebitCard/bridgeCard/card.tsx, src/i18n/index.tsx
- KeyboardAware ChooseChountry and ChooseState modals. Fix glitching card bgImage. Change Send OTP text. StateFilter works now. Show upgrade only in PC. and more.
=> fix: :bug: UpgradeToPhysicalCardScreenBugs and changes

src/components/v2/CardCarousel.tsx, src/containers/DebitCard/CardV2/ShippingDetailsOTPScreen.tsx, src/containers/DebitCard/bridgeCard/card.tsx
Used FlatList inversion to handle the cardIndex issue for the CardsCarousel, corrected the conditonal response handling in the triggerOtp function in the ShippingDetailsOTPScreen
=> fix: :bug: cardIndex issue, OTP response handling issue

src/components/ChooseChainModal.tsx, src/components/v2/OTPInput.tsx
…t placeholder
When removing the cosmos chains from the Portfolio chain filter, evmos was also removed. This has been reverted. Changed the text from Enter PIN to Enter OTP for the OTPInput textinput component.
=> CYP-1663-add-evmos-to-track-wallet-choose-chain

src/components/v2/portfolioTokenItem.tsx, src/containers/Portfolio/index.tsx, src/containers/Portfolio/scenes/tokenScene.tsx, src/containers/TokenOverview/index.tsx, src/containers/TokenOverview/overview.tsx, src/i18n/index.tsx
Added a section under token overview to show the same token across chains.
=> CYP-1676-TokenOverview-enhancements

App.tsx
Removed the the exit app call after clicking update when the update is prompted.
This fixes the issue that made it look like the app was crashing when update is clicked.
=> fix: :bug: inapp update crashing the app

src/core/globalContext.tsx
Change the Staking Balance RPC for Evmos since the previous is down now.
Evmos staking page appears now.
=> fix: :alien: change evmos

src/containers/Bridge/bridge.tsx
The gas was calculated only when the value is lesser than the actualBalance. Changed it to calculate for lesser than or equal to actualBalance.
This fixes gas showing as 0 when Max is used to fill the input field.
=> fix: :bug: gas calculation when max is clicked.

src/containers/AddressBook/myAddress.tsx, src/containers/Qrcode/index.tsx
Streamlined the font size. Moved the action buttons. Added masked and full address.
=> feat: :sparkles: receive page enhancement

src/containers/Portfolio/scenes/tokenScene.tsx
Reordering the portfolio token list when the position of a token changes due to increase or decrease in its value.
This fixes the higher totalValue tokens being lower in the list after an activity happens.
=> fix: :adhesive_bandage: reorder the tokens on position change

src/containers/TokenOverview/overview.tsx
Token overview page now only refreshes after staking page has been opened.
This fixes balance displaying as 0 in Token Overview page for Cosmos tokens.
=> fix: :bug: token overview refresh bug

src/components/v2/tokenAmount.tsx, src/components/v2/tokenValue.tsx
disabled the onPress of the TokenAmount and TokenValue fields outside of Privacy mode being enabled
=> CYP-1731-Privacy-toggle-disabled-outside-privacy-mode

src/components/BottomTokenCardConfirm.tsx, src/constants/cardPageV2.ts, src/constants/server.tsx, src/containers/DebitCard/bridgeCard/fundCard.tsx, src/core/NativeTransactionHandler.ts, src/i18n/index.tsx, src/models/card.model.ts
Integration of the new max load card quote API that works 99% of the time and various improvements in code.
This fixes Max Quoted card loads failing most of the times.
=> feat: :sparkles: max API integration

src/components/BottomTokenCardConfirm.tsx, src/components/v2/tokenAmount.tsx, src/containers/TokenOverview/overview.tsx, src/routes/tabStack.tsx
Changed the condition for when the token across chain is empty to correctly display the message.
This fixes empty token across chains showing nothing.
=> fix: :adhesive_bandage: token across chains section empty case

src/containers/DebitCard/bridgeCard/card.tsx
Fixed the proportions of the progress bar, changed to 100% after the progress bar hits 100%
This fixes the progress bar showing progress beyond 100%
=> fix: :bug: upgrade to physical card progress bar

src/containers/DebitCard/cardSignupLanding.tsx, src/containers/Portfolio/components/BannerCarousel/BannerCarouselItem.tsx, src/routes/tabStack.tsx
Brought back old tabbar and padded the concerned screen: Invite card screen.
This fixes TabBar looking weird for Android.
=> fix: :bug: android tabbar disfigured

package-lock.json, package.json, src/constants/config.ts, src/containers/AddressBook/createContact.tsx, src/containers/AddressBook/myAddress.tsx, src/containers/CosmosStaking/action.tsx, src/containers/DebitCard/bridgeCard/fundCard.tsx, src/containers/Options/PrivateKey.tsx, src/containers/Options/hostsAndRPC.tsx, src/containers/TokenOverview/staking.tsx, src/containers/utilities/cosmosSendUtility.ts, src/core/Address.ts, src/core/NativeTransactionHandler.ts, src/core/push.tsx, src/hooks/useGasService/index.tsx, src/hooks/useTransactionManager/index.tsx, src/i18n/index.tsx, src/reducers/cosmosStakingReducer.tsx
JIRA ticket: https://cypherd.atlassian.net/browse/CYP-2054
=> Fixed Coreum browser connect issue, and gas fee denom for all chains

src/containers/DebitCard/CardV2/index.tsx, src/i18n/index.tsx
intermediate step before shipping added
=> fix: shipping status change

src/containers/Browser/Browser.tsx, src/containers/SendTo/enterAmount.tsx, src/containers/Staking/delegation.tsx, src/containers/TokenOverview/staking.tsx
JIRA: https://cypherd.atlassian.net/browse/CYP-2056?atlOrigin=eyJpIjoiZmI3MWE4Yjg5YzIxNDRmYzhmODhkZjhhZTc5NWUzNDEiLCJwIjoiaiJ9
=> removed buy or bridge modal

src/components/StakeOptionsModal.tsx, src/constants/cosmosConfig.ts, src/containers/Staking/delegation.tsx, src/containers/Staking/reDelegate.tsx, src/containers/Staking/reStake.tsx, src/containers/TokenOverview/staking.tsx, src/core/NativeTransactionHandler.ts, src/hooks/useGasService/index.tsx
JIRA: https://cypherd.atlassian.net/browse/CYP-2063?atlOrigin=eyJpIjoiYjIzMGQ2YTU2MmZiNDFmNjljNDAyMTE4ZDZhNmE2NGUiLCJwIjoiaiJ9
=> Fixed evmos staking issue

src/containers/Bridge/bridge.tsx, src/containers/Portfolio/constants.ts, src/core/swap.ts
fix: ODOS SWAP
Error: Transaction has been reverted by the EVM:
{
"blockHash": "0x0e9386e0d4bf6b2cbe75588a522c5b8be5d3dde61ae594ea8bfba942012b1b30",
"blockNumber": 57174569,
"contractAddress": null,
"cumulativeGasUsed": 295593,
"effectiveGasPrice": 63600000133,
"from": "0x1940821a0875867d32de4d6da184574cafbdc491",
"gasUsed": 25836,
"logs": [
{
"address": "0x0000000000000000000000000000000000001010",
"topics": [
"0x4dfe1bbbcf077ddc3e01291eea2d5c70c2b422b415d95645b9adcfd678cb1d63",
"0x0000000000000000000000000000000000000000000000000000000000001010",
"0x0000000000000000000000001940821a0875867d32de4d6da184574cafbdc491",
"0x000000000000000000000000a8b52f02108aa5f4b675bdcc973760022d7c6020"
],
"data": "0x0000000000000000000000000000000000000000000000000005d6743c5441380000000000000000000000000000 …
=> fix: odos swap msg.value wrong

src/components/v2/portfolioTokenItem.tsx, src/containers/Qrcode/index.tsx, src/containers/Shortcuts/index.tsx, src/containers/TokenOverview/toolbar.tsx
**JIRA:** https://cypherd.atlassian.net/browse/CYP-2104
=> fixed all the coreum address displayed in APP

App.tsx, src/components/initializeAppProvider/index.tsx, src/hooks/useInitializer/index.tsx, src/routes/tabStack.tsx
Changed `authToken === undefined`  to `isEmpty(authToken)` since authToken is of type string and it was not given a default value in the initial context state it was taken as undefined but since I defined it as empty string the comparison `authToken === undefined` started failing, so which triggered other flows resulting in calling calling get token multiple times creating a mess up.
=> fixed the register call failure

src/containers/AddressBook/addressProfile.tsx, src/containers/AddressBook/contacts.tsx, src/containers/SendTo/index.tsx
Fixed delete contaact bug
Fixed app crashing when we select create new contact from send to success modal
=> fix: create contact and delete contact

src/containers/DebitCard/bridgeCard/cardOptions.tsx, src/containers/DebitCard/bridgeCard/cardRevealAuth.tsx, src/containers/DebitCard/bridgeCard/setPin.tsx
Pin setting for RC card done along proper error validation using formik and yup
=> feat: pin setting for reap card done

src/components/v2/activityBridgeInfoModal.tsx, src/components/v2/formikDatePicker.tsx, src/containers/Activities/activity.tsx, src/containers/Bridge/index.tsx, src/containers/Bridge/tokenSelection.tsx, src/containers/DebitCard/CardV2/signup/otpVerification.tsx, src/containers/DebitCard/CardV2/signup/telegramSetup.tsx, src/containers/DebitCard/bridgeCard/card.tsx, src/containers/Options/referrals.tsx, src/containers/Portfolio/index.tsx, src/containers/Portfolio/scenes/txnScene.tsx, src/containers/SendTo/index.tsx, src/containers/TokenOverview/overview.tsx, src/core/HttpRequest.ts, src/core/util.tsx, src/hooks/useEthSigner/index.tsx, src/reducers/activity_reducer.tsx, src/routes/tabStack.tsx
=> Bridge bug fix (#445)

src/containers/DebitCard/CardV2/globalOptions.tsx, src/containers/DebitCard/CardV2/index.tsx
=> changed the global account options in card

ios/Cypherd/Info.plist, src/components/v2/chooseTokenModalV2.tsx, src/containers/DebitCard/CardV2/index.tsx, src/containers/DebitCard/bridgeCard/fundCard.tsx, src/containers/DebitCard/bridgeCard/quote.tsx, src/core/skipApi.ts, src/core/util.tsx, src/models/card.model.ts
* changed comsos card load to use cosmosswap.amountIn instead of tokensRequired
* removed console logs
* ios version bump
* added check for empty address list
=> Cyq 104 (#667)

src/components/initializeAppProvider/index.tsx, src/components/walletConnectListener/index.tsx, src/containers/DebitCard/bridgeCard/quote.tsx, src/containers/OnBoarding/onBoardOpotions.tsx, src/core/util.tsx, src/hooks/useInitializer/index.tsx, src/models/analytics.interface.ts, src/notification/pushNotification.ts
* added signin with apple id and the fcm token logic
* fixes
* code rabbit fix
=> added sign-in with apple id and the fcm token logic (#744)
